### ISSUE TITLE
Download Link not working

### ISSUE THREAD

**Issue by mhegering** [Artemis-RGB/Artemis.Plugins.HardwareMonitors#22]
Hey Guys, after updating Artemis the Plugin was gone. Wanted to redownload it but the link isn't working.
![Screenshot 2024-03-01 100306](https://github.com/Artemis-RGB/Artemis.Plugins.HardwareMonitors/assets/77127341/ddf1926e-cad7-4578-9139-09007412a52c)

**Comment by diogotr7** [comment]
Please download the plugins from the in-app workshop, I have published them there instead of distributing them here.
